## Simple Kubernetes manifest for a production ready metabase setup using a MySql database.
## Insert your DB hostname, username and password below.
## To use Postgres, simply change MB_DB_TYPE to postgress and MB_DB_PORT to your postgress port (default is 5432).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      name: metabase
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_TYPE
              value: mysql
            - name: MB_DB_DBNAME
              value: metabase
            - name: MB_DB_PORT
              value: "3306"
            - name: MB_DB_USER
              value: <your_DB_username>
            - name: MB_DB_PASS
              value: <your_DB_password>
            - name: MB_DB_HOST
              value: <your_DB_hostname>
