name: "Terraform action"
on:
  push:
    branches:
      - main
 
env:
  TF_LOG: INFO
  AWS_REGION: us-east-2
jobs:
  deploy-serverless:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: serverless
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Ensure docs directory
        run: mkdir test-repo

      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          repository:  getir-dev/david-igbinedion-serverless-application
          token: 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 #should be stored as a secret but I don't have admin access to do so
          path: test-repo/lambda
          ref: main

      - name: List directory
        run: cd

      - name: Zip code
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r test-repo.zip test-repo/lambda

      - name: List directory
        run: ls 
